-- KORZH FAN / City fan system
-- Run once in Supabase SQL Editor.
create table if not exists public.city_fans (
  id bigint generated by default as identity primary key,
  city text not null check (length(trim(city)) between 2 and 60),
  visitor_id text not null check (length(trim(visitor_id)) between 16 and 80),
  created_at timestamptz not null default now()
);

create unique index if not exists city_fans_visitor_city_idx
  on public.city_fans(visitor_id, city);
create index if not exists city_fans_city_idx
  on public.city_fans(city);

alter table public.city_fans enable row level security;

drop policy if exists city_fans_public_insert on public.city_fans;
create policy city_fans_public_insert on public.city_fans
  for insert to anon, authenticated
  with check (
    length(trim(city)) between 2 and 60
    and length(trim(visitor_id)) between 16 and 80
  );

-- Do not expose visitor IDs to the public. Return only aggregated city counts.
create or replace function public.city_leaderboard()
returns table(city text, fans bigint)
language sql
security definer
set search_path = public
stable
as $$
  select cf.city, count(*)::bigint as fans
  from public.city_fans cf
  group by cf.city
  order by count(*) desc, lower(cf.city) asc
  limit 100;
$$;

grant execute on function public.city_leaderboard() to anon, authenticated;
grant insert on public.city_fans to anon, authenticated;

-- Optional cleanup helper for admins only.
create or replace function public.is_city_fan(visitor text, selected_city text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists(
    select 1 from public.city_fans
    where visitor_id = visitor and city = selected_city
  );
$$;
grant execute on function public.is_city_fan(text,text) to anon, authenticated;
