-- KORZH FAN / Supabase database
-- Run this whole file once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role in ('admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.stories (
  id uuid primary key default gen_random_uuid(),
  name text not null default 'Аноним',
  city text not null default 'Город не указан',
  text text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  moderated_at timestamptz,
  moderated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  page text,
  session_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.city_fans (
  id bigint generated by default as identity primary key,
  city text not null check (length(trim(city)) between 2 and 60),
  visitor_id text not null check (length(trim(visitor_id)) between 16 and 80),
  created_at timestamptz not null default now()
);

create unique index if not exists stories_status_created_idx on public.stories(status, created_at desc);
create index if not exists analytics_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_type_idx on public.analytics_events(event_type);
create index if not exists analytics_session_idx on public.analytics_events(session_id);
create unique index if not exists city_fans_visitor_city_idx on public.city_fans(visitor_id, city);
create index if not exists city_fans_city_idx on public.city_fans(city);

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public stable as $$
  select exists (select 1 from public.admin_profiles where user_id = auth.uid() and role = 'admin');
$$;

create or replace function public.city_leaderboard()
returns table(city text, fans bigint)
language sql security definer set search_path = public stable as $$
  select cf.city, count(*)::bigint as fans
  from public.city_fans cf
  group by cf.city
  order by count(*) desc, lower(cf.city) asc
  limit 100;
$$;

grant execute on function public.city_leaderboard() to anon, authenticated;

a lter table public.admin_profiles enable row level security;
alter table public.stories enable row level security;
alter table public.analytics_events enable row level security;
alter table public.city_fans enable row level security;

drop policy if exists admin_profile_self on public.admin_profiles;
create policy admin_profile_self on public.admin_profiles for select to authenticated using (user_id = auth.uid());

drop policy if exists stories_public_insert on public.stories;
create policy stories_public_insert on public.stories for insert to anon, authenticated with check (status = 'pending' and length(trim(name)) between 1 and 40 and length(trim(city)) between 1 and 40 and length(trim(text)) between 20 and 1200);

drop policy if exists stories_public_read_approved on public.stories;
create policy stories_public_read_approved on public.stories for select to anon, authenticated using (status = 'approved' or public.is_admin());

drop policy if exists stories_admin_update on public.stories;
create policy stories_admin_update on public.stories for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists stories_admin_delete on public.stories;
create policy stories_admin_delete on public.stories for delete to authenticated using (public.is_admin());

drop policy if exists analytics_insert on public.analytics_events;
create policy analytics_insert on public.analytics_events for insert to anon, authenticated with check (length(event_type) between 1 and 80);

drop policy if exists analytics_admin_read on public.analytics_events;
create policy analytics_admin_read on public.analytics_events for select to authenticated using (public.is_admin());

drop policy if exists analytics_admin_delete on public.analytics_events;
create policy analytics_admin_delete on public.analytics_events for delete to authenticated using (public.is_admin());

drop policy if exists city_fans_public_insert on public.city_fans;
create policy city_fans_public_insert on public.city_fans for insert to anon, authenticated with check (length(trim(city)) between 2 and 60 and length(trim(visitor_id)) between 16 and 80);

-- Public city stats are returned only as aggregates; visitor IDs are never exposed.
grant select on public.stories to anon, authenticated;
grant insert on public.stories to anon, authenticated;
grant update, delete on public.stories to authenticated;
grant select on public.analytics_events to authenticated;
grant insert on public.analytics_events to anon, authenticated;
grant delete on public.analytics_events to authenticated;
grant select on public.admin_profiles to authenticated;
grant insert on public.city_fans to anon, authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

-- After creating your admin in Authentication -> Users, insert that user's UUID into admin_profiles.
-- insert into public.admin_profiles (user_id) values ('YOUR-AUTH-USER-UUID');
