const quiz=[
 {q:'Тебе пишут: «Поехали прямо сейчас». Твоя реакция?',a:[['Куда угодно. Я уже в пути.','adventure'],['Сначала план, потом движение.','drive'],['Если свои — едем.','loyalty'],['Мне бы тишины и дороги.','night']]},
 {q:'Идеальный вечер — это…',a:[['Громко, много людей, много движения.','party'],['Машина, город и разговоры до ночи.','romance'],['Друзья, свой круг и без лишних.','loyalty'],['Один маршрут и свои мысли.','night']]},
 {q:'Что для тебя важнее всего?',a:[['Свобода делать по-своему.','freedom'],['Люди, которые рядом.','loyalty'],['Цель, к которой идёшь.','drive'],['Чувства и настоящие моменты.','romance']]},
 {q:'Если всё пошло не по плану…',a:[['Импровизирую.','adventure'],['Собираюсь и исправляю.','drive'],['Звоню своим.','loyalty'],['Ухожу на прогулку и перезагружаюсь.','night']]},
 {q:'Твой главный режим?',a:[['«Давайте ещё один круг».','party'],['«Не знаю куда, но поехали».','adventure'],['«У меня есть план».','drive'],['«Главное — чтобы было по-настоящему».','romance']]},
 {q:'Что ты ценишь в людях?',a:[['Честность.','freedom'],['Верность.','loyalty'],['Характер.','drive'],['Умение чувствовать.','romance']]},
 {q:'Тебе дают свободный день. Что выберешь?',a:[['Новый город без маршрута.','adventure'],['Большую компанию и движ.','party'],['Дорогу, музыку и ночь.','night'],['Сделаю то, что давно откладывал.','freedom']]}
];
const types={freedom:{title:'СВОБОДНЫЙ',text:'Тебе тесно в чужих рамках. Ты выбираешь свой маршрут и не любишь, когда за тебя решают.',tags:['Свобода','Характер','Свой путь']},drive:{title:'ПАЦАН С ПЛАНОМ',text:'У тебя внутри двигатель. Если решил — двигаешься. Даже когда маршрут приходится менять на ходу.',tags:['Драйв','Цель','Характер']},loyalty:{title:'СВОЙСКИЙ',text:'Для тебя важны люди. Свой круг, честность и ощущение, что рядом те, на кого можно рассчитывать.',tags:['Свои','Верность','Команда']},night:{title:'НОЧНОЙ БЕГЛЕЦ',text:'Тебе нужна дорога, воздух и время без лишнего шума. Иногда лучший разговор — тот, что происходит внутри.',tags:['Ночь','Дорога','Мысли']},romance:{title:'РОМАНТИК',text:'Ты замечаешь моменты, которые другие пропускают. Для тебя важны чувства, атмосфера и настоящие истории.',tags:['Чувства','Моменты','Истории']},party:{title:'ДВИЖОВЫЙ',text:'Там, где ты — там жизнь. Ты умеешь превращать обычный вечер в историю, которую потом вспоминают.',tags:['Движ','Энергия','Люди']},adventure:{title:'ВЕЧНО В ПУТИ',text:'Сидеть на месте — не твой стиль. Новая дорога, новый город, новый поворот — и уже интересно.',tags:['Путь','Новое','Свобода']}};
let step=0,scores={freedom:0,drive:0,loyalty:0,night:0,romance:0,party:0,adventure:0};
const $=id=>document.getElementById(id);
function resetScores(){Object.keys(scores).forEach(k=>scores[k]=0);}
function render(){const item=quiz[step];$('questionNumber').textContent=`ВОПРОС ${String(step+1).padStart(2,'0')} / ${quiz.length}`;$('progressText').textContent=Math.round(((step+1)/quiz.length)*100)+'%';$('progressBar').style.width=((step+1)/quiz.length)*100+'%';$('quizContent').innerHTML=`<h2 class="question">${item.q}</h2><div class="answers">${item.a.map((x,i)=>`<button class="answer" data-i="${i}">${x[0]}</button>`).join('')}</div>`;document.querySelectorAll('.answer').forEach(b=>b.addEventListener('click',()=>choose(+b.dataset.i)));}
function choose(i){scores[quiz[step].a[i][1]]++;step++;if(step<quiz.length)render();else showResult();}
function resultMarkup(top,score){const type=types[top];$('resultScore').textContent=score;$('resultTitle').textContent=type.title;$('resultText').textContent=type.text;$('resultBars').innerHTML=type.tags.map((tag,i)=>`<div class="bar"><span>${tag}</span><div class="bar-line"><i style="width:${90-i*18}%"></i></div><b>${90-i*18}%</b></div>`).join('');}
function showResult(){const entries=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const top=entries[0][0],raw=entries[0][1];const score=Math.min(100,Math.max(60,Math.round(60+(raw/quiz.length)*40)));$('quizCard').classList.add('hidden');$('resultCard').classList.remove('hidden');resultMarkup(top,score);localStorage.setItem('korzhResult',JSON.stringify({score,title:types[top].title,type:top}));history.replaceState(null,'',`${location.pathname}?result=${top}&score=${score}`);window.scrollTo({top:$('resultCard').offsetTop-80,behavior:'smooth'});}
function challengeText(){return `Я набрал ${$('resultScore').textContent}/100 в KORZH FAN — «${$('resultTitle').textContent}». А ты на сколько Корж? Проверь себя: ${location.href}`;}
async function shareChallenge(){const text=challengeText();try{if(navigator.share){await navigator.share({title:'На сколько ты Корж?',text,url:location.href});$('shareNote').textContent='Вызов отправлен 🔥';}else{await navigator.clipboard.writeText(text);$('shareNote').textContent='Вызов скопирован. Отправляй другу 🔥';}}catch(e){if(e.name!=='AbortError')$('shareNote').textContent='Не получилось открыть меню — нажми «Скопировать вызов».';}}
async function copyChallenge(){try{await navigator.clipboard.writeText(challengeText());$('shareNote').textContent='Готово. Вызов скопирован — отправляй в TikTok, Telegram или другу 🔥';}catch(e){$('shareNote').textContent='Скопируй ссылку из адресной строки и отправь другу.';}}
$('shareBtn').addEventListener('click',shareChallenge);
$('copyBtn').addEventListener('click',copyChallenge);
$('restartBtn').addEventListener('click',()=>{step=0;resetScores();$('resultCard').classList.add('hidden');$('quizCard').classList.remove('hidden');$('shareNote').textContent='';history.replaceState(null,'',location.pathname+'#test');render();document.getElementById('test').scrollIntoView({behavior:'smooth'});});
const params=new URLSearchParams(location.search);const shared=params.get('result');if(shared&&types[shared]){$('quizCard').classList.add('hidden');$('resultCard').classList.remove('hidden');resultMarkup(shared,Math.min(100,Math.max(60,Number(params.get('score'))||60)));}else render();
