const quiz=[{q:'Тебе пишут: «Поехали прямо сейчас». Твоя реакция?',a:[['Куда угодно. Я уже в пути.','adventure'],['Сначала план, потом движение.','drive'],['Если свои — едем.','loyalty'],['Мне бы тишины и дороги.','night']]},{q:'Идеальный вечер — это…',a:[['Громко, много людей, много движения.','party'],['Машина, город и разговоры до ночи.','romance'],['Друзья, свой круг и без лишних.','loyalty'],['Один маршрут и свои мысли.','night']]},{q:'Что для тебя важнее всего?',a:[['Свобода делать по-своему.','freedom'],['Люди, которые рядом.','loyalty'],['Цель, к которой идёшь.','drive'],['Чувства и настоящие моменты.','romance']]},{q:'Если всё пошло не по плану…',a:[['Импровизирую.','adventure'],['Собираюсь и исправляю.','drive'],['Звоню своим.','loyalty'],['Ухожу на прогулку и перезагружаюсь.','night']]},{q:'Твой главный режим?',a:[['«Давайте ещё один круг».','party'],['«Не знаю куда, но поехали».','adventure'],['«У меня есть план».','drive'],['«Главное — чтобы было по-настоящему».','romance']]},{q:'Что ты ценишь в людях?',a:[['Честность.','freedom'],['Верность.','loyalty'],['Характер.','drive'],['Умение чувствовать.','romance']]},{q:'Тебе дают свободный день. Что выберешь?',a:[['Новый город без маршрута.','adventure'],['Большую компанию и движ.','party'],['Дорогу, музыку и ночь.','night'],['Сделаю то, что давно откладывал.','freedom']]}];
const types={freedom:['СВОБОДНЫЙ','Тебе тесно в чужих рамках. Ты выбираешь свой маршрут.',['Свобода','Характер','Свой путь']],drive:['ПАЦАН С ПЛАНОМ','У тебя внутри двигатель. Если решил — двигаешься.',['Драйв','Цель','Характер']],loyalty:['СВОЙСКИЙ','Для тебя важны люди, свой круг и верность.',['Свои','Верность','Команда']],night:['НОЧНОЙ БЕГЛЕЦ','Тебе нужна дорога, воздух и время без лишнего шума.',['Ночь','Дорога','Мысли']],romance:['РОМАНТИК','Ты замечаешь моменты, которые другие пропускают.',['Чувства','Моменты','Истории']],party:['ДВИЖОВЫЙ','Там, где ты — там жизнь. Ты умеешь создавать историю.',['Движ','Энергия','Люди']],adventure:['ВЕЧНО В ПУТИ','Новая дорога, новый город, новый поворот — и уже интересно.',['Путь','Новое','Свобода']]};
const $=id=>document.getElementById(id);let step=0,scores={};Object.keys(types).forEach(k=>scores[k]=0);
function markup(type,score){const d=types[type];$('resultScore').textContent=score;$('resultTitle').textContent=d[0];$('resultText').textContent=d[1];$('cardScore').textContent=score;$('cardType').textContent=d[0];$('typeTags').innerHTML=d[2].map(x=>`<span>${x}</span>`).join('');$('resultBars').innerHTML=d[2].map((x,i)=>`<div class="bar"><span>${x}</span><div class="bar-line"><i style="width:${90-i*18}%"></i></div><b>${90-i*18}%</b></div>`).join('');}
function render(){const q=quiz[step];$('questionNumber').textContent=`ВОПРОС ${String(step+1).padStart(2,'0')} / 07`;$('progressText').textContent=Math.round((step+1)/7*100)+'%';$('progressBar').style.width=((step+1)/7*100)+'%';$('quizContent').innerHTML=`<h2 class="question">${q.q}</h2><div class="answers">${q.a.map((x,i)=>`<button class="answer" data-i="${i}">${x[0]}</button>`).join('')}</div>`;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>choose(+b.dataset.i));}
function choose(i){scores[quiz[step].a[i][1]]++;step++;step<quiz.length?render():showResult();}
function showResult(){const sorted=Object.entries(scores).sort((a,b)=>b[1]-a[1]);const type=sorted[0][0],score=Math.min(100,Math.max(60,Math.round(60+sorted[0][1]/7*40)));markup(type,score);$('quizCard').classList.add('hidden');$('resultCard').classList.remove('hidden');const stats=JSON.parse(localStorage.getItem('korzhTypeStats')||'{}');stats[type]=(stats[type]||0)+1;localStorage.setItem('korzhTypeStats',JSON.stringify(stats));history.replaceState(null,'',`test.html?result=${type}&score=${score}`);window.scrollTo({top:0,behavior:'smooth'});}
function challenge(){return `Я набрал ${$('resultScore').textContent}/100 в KORZH FAN — «${$('resultTitle').textContent}». А ты на сколько Корж? ${location.origin}${location.pathname}`;}
$('shareBtn').onclick=async()=>{try{if(navigator.share)await navigator.share({title:'На сколько ты Корж?',text:challenge(),url:location.href});else await navigator.clipboard.writeText(challenge());$('shareNote').textContent='Вызов отправлен 🔥';}catch(e){if(e.name!=='AbortError')$('shareNote').textContent='Скопируй вызов вручную.';}};
$('copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(challenge());$('shareNote').textContent='Готово. Отправляй другу 🔥';}catch(e){$('shareNote').textContent='Скопируй ссылку из адресной строки.';}};
function downloadCard(){const c=document.createElement('canvas');c.width=1080;c.height=1350;const x=c.getContext('2d');const g=x.createRadialGradient(850,220,20,500,700,1000);g.addColorStop(0,'#5b1714');g.addColorStop(.4,'#171010');g.addColorStop(1,'#070707');x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.strokeStyle='#5b2925';x.lineWidth=3;x.strokeRect(34,34,1012,1282);x.fillStyle='#aaa';x.font='700 30px Arial';x.fillText('KORZH FAN',70,105);x.font='700 24px Arial';x.fillText('RESULT / 2026',780,105);x.fillStyle='#c8c4bc';x.font='700 26px Arial';x.fillText('НАСКОЛЬКО ТЫ КОРЖ?',70,330);x.fillStyle='#ef3d35';x.font='700 250px Arial';x.fillText($('resultScore').textContent,70,600);x.fillStyle='#777';x.font='700 46px Arial';x.fillText('/100',600,590);x.fillStyle='#f2f0e9';x.font='700 68px Arial';x.fillText($('resultTitle').textContent,70,760);x.fillStyle='#8c8882';x.font='700 25px Arial';x.fillText('ПРОВЕРЬ ДРУГА',70,1210);x.fillText('KORZH FAN • KF.001',760,1210);const a=document.createElement('a');a.download='korzh-fan-result.png';a.href=c.toDataURL('image/png');a.click();$('shareNote').textContent='Карточка сохранена 🔥';}
$('downloadCardBtn').onclick=downloadCard;$('downloadCardBtn2').onclick=downloadCard;$('restartBtn').onclick=()=>{step=0;Object.keys(scores).forEach(k=>scores[k]=0);$('resultCard').classList.add('hidden');$('quizCard').classList.remove('hidden');history.replaceState(null,'','test.html');render();};$('menuBtn').onclick=()=>document.body.classList.toggle('menu-open');document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>document.body.classList.remove('menu-open'));
const p=new URLSearchParams(location.search);if(p.get('result')&&types[p.get('result')]){$('quizCard').classList.add('hidden');$('resultCard').classList.remove('hidden');markup(p.get('result'),Math.min(100,Math.max(60,+p.get('score')||60)));}else render();